Домашнее задание №2
Frontend-Sirius-VK/2022-autumn-s.ryndin pull request #2
Opened 2022-12-03 15:32 UTC by Naziser

2022-12-06 18:58 UTC, StealthTech requested changes
Приложи, пожалуйста, скриншот, как выглядит проект с подключенной базой данных

2022-12-06 18:58 UTC, StealthTech commented on server.js
> +const db = require('./src/dataBase.js')
database обычно пишут без выделения слова base

2022-12-06 18:58 UTC, StealthTech commented on server.js
>      // TODO
login можно убрать, сократили требования

2022-12-06 18:58 UTC, StealthTech commented on src/components/header/HeaderBlock.js
> +    }
Рекомендую перенести на handlebars

2022-12-06 18:58 UTC, StealthTech commented on src/components/header/header.css
> +    box-shadow: 0 1px 2px hsla(0,0%,0%,0.05), 0 1px 4px hsla(0,0%,0%,0.05), 0 2px 8px hsla(0,0%,0%,0.05);
Не хватает пробелов. Давай цвета вынесем отдельно в палитру в CSS Custom Properties

2022-12-06 18:58 UTC, StealthTech commented on src/components/header/header.css
> +header .header-logo {
Селекторы по тегу — антипаттерн. Лучше использовать БЭМ: https://ru.bem.info/methodology/quick-start

2022-12-06 18:58 UTC, StealthTech commented on src/components/header/header.css
> +    min-width: 236px;
Использовать размеры в px с точностью до пикселя не рекомендую нигде кроме картинок (напр. 236px — не ок, 240px — ок)

2022-12-06 18:58 UTC, StealthTech commented on src/components/header/header.css
> +    border-color: var(--buttons-border-color);
круто! остальные тоже надо перенести в палитру)

2022-12-06 18:58 UTC, StealthTech commented on src/main.css
> +:root {
Вот здесь можно организовать палитру

2022-12-06 18:58 UTC, StealthTech commented on src/components/questionBlock/QuestionBlock.js
> +}
Стоит добавлять пустые строки в конце файла: https://semakin.dev/2020/05/no_newline_at_end_of_file/

2022-12-06 18:58 UTC, StealthTech commented on src/components/questionBlock/questions.css
> +    -webkit-line-clamp: 2;
Зачем это свойство?

2022-12-06 18:58 UTC, StealthTech commented on src/dataBase.js
> +    password: '123',
В учебном проекте ОК, но в реальном проекте **никогда** не постим в публичный гит логины/пароли

2022-12-06 18:58 UTC, StealthTech commented on src/index.html
> +    <link rel="stylesheet" href="src/main.css">
link лучше в head, чтобы загрузить перед отрисовкой страницы

2022-12-06 18:58 UTC, StealthTech commented on src/models/Question.js
> +                                })
Тут что-то случилось с отступами

2022-12-06 18:58 UTC, StealthTech commented on src/routing/Router.js
> +                this.stop();
Почему так?

2022-12-06 19:34 UTC, Naziser commented on src/components/questionBlock/questions.css
> +    -webkit-line-clamp: 2;
Это чтобы в описании вопроса текст не выводился полностью . Благодаря этому свойству выводится только 2 строки текста, а дальше идет троеточие

2022-12-06 19:35 UTC, Naziser commented on src/routing/Router.js
> +                this.stop();
а иначе у меня верстка дублируется при нажатии на любую из ссылок :(

2022-12-06 20:07 UTC, StealthTech commented on src/routing/Router.js
> +                this.stop();
Надо по-другому решить — придется же потом делать другую страницу

2022-12-08 19:29 UTC, StealthTech requested changes

2022-12-08 19:29 UTC, StealthTech commented on src/components/header/header.css
> +header {
Писал в прошлой пачке комментариев, что селекторы по тегу — антипаттерн. Давай переделаем на классы

2022-12-08 19:29 UTC, StealthTech commented on src/main.css
> +    --post-links_color: hsl(206, 100%, 40%);
Лучше соблюдать dash-case нотацию, без подчеркиваний, иначе в некоторых случаях выглядит как snake_case совсем

2022-12-08 20:04 UTC, Naziser commented on src/components/header/header.css
> +header {
переделал

2022-12-08 20:04 UTC, Naziser commented on src/main.css
> +    --post-links_color: hsl(206, 100%, 40%);
исправил

2022-12-09 15:36 UTC, StealthTech approved these changes

2022-12-09 15:40 UTC, merged

2022-12-10 07:46 UTC, StealthTech commented
![telegram-cloud-photo-size-2-5224595195100774840-y](https://user-images.githubusercontent.com/5190765/206839238-c7839743-4737-43bb-a485-03dbc6c4022d.jpg)